### ISSUE TITLE
Демонстрация результата: до/после и тестовые urls

### ISSUE THREAD

**Issue by egslava** [ri-gilfanov/runet-filters#1]
Здравствуйте! :)

Посмотрел на код очень неплохая идея! Попробовал вставить в uBlock Origin и набрать "Байден" на YouTube'е. Тем не менее, увидел имя/фамилию, хотя, вроде, она должна была быть заблокирована. Поэтому было бы интересно увидеть предполагаемый/ожидаемый результат до/после в README.md

**Comment by rigilfanov** [comment]
@egslava, если по порядку.

1) Убедитесь, что нужные Вам фильтры включены:
![Снимок экрана от 2021-09-07 17-53-31](https://user-images.githubusercontent.com/29487864/132348836-fe404477-e9b2-4786-b328-9f7bf4127b7e.png)

2) Если Вы открыли страницу YouTube в Firefox до того как включили фильтры, попробуйте сочетание Ctrl+F5.

3) Если Вы решили искать что-то из того, что фильтруется, можно наблюдать борьбу uBlockOrigin с автоматической подгрузкой. А именно, мелькание плиток с видео и/или долго крутящийся спиннер:
![Снимок экрана от 2021-09-07 17-56-23](https://user-images.githubusercontent.com/29487864/132349332-9ee0ebf6-4865-4370-8d5b-920522192b7e.png)

4) Если скрытых плиток становится слишком много (десятки, сотни, тысячи), то uBlockOrigin может начать глючить и при прокрутке скрытое будет то появляться, то скрываться.

5) В конечном счёте, будет показано то, что проскочило через регулярное выражение:
![Снимок экрана от 2021-09-07 17-58-10](https://user-images.githubusercontent.com/29487864/132349647-cc43cec6-ac66-4974-b6ee-d3cce5286d52.png)
В первой плитке с видео сочетания Байден нет. Во второй фильтр не сработал из-за слеша перед буквой Б.

6) Если Вы хотите найти то, что скрывается одним из фильтров -- лучше отключите соответствующий список фильтров.

7) Фильтры куда более полезны при просмотре рекомендаций на главной страницы YouTube, просмотре видео отдельных каналов и списка похожих видео:
![Снимок экрана от 2021-09-07 18-15-16](https://user-images.githubusercontent.com/29487864/132351135-5a729b37-7baf-4c37-a273-2cc470782cc6.png)
В списке видео отдельных каналов Вы часто можете наблюдать пустые пространства, что остались от скрытых видео. Впрочем, если скрыт целый ряд -- пустое пространство схлопывается.

8) На главной странице с рекомендациями пустых пространств я сейчас не наблюдаю. Либо YouTube изменил вёрстку и теперь все пустые пространства схлопываются, либо YouTube перестал предлагать мне фильтруемый контент.

Чуть позднее постараюсь добавить в README.rst более-менее наглядные скрины работы фильтров в YouTube и VK.

**Update**. Так же из-за работающих фильтров иногда не показываются видео на главных страницах YouTube каналов, но Вы можете нажать на вкладку видео и найти то, что нужно.

**Comment by egslava** [comment]
Воу! Клёво! :)

Да, спасибо, всё работает, прошу прощения за беспокойство :)
